# Generated by Django 3.2.19 on 2023-12-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
