# Generated by Django 3.2.19 on 2024-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_membership_is_ghost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='host_policy',
            field=models.CharField(choices=[('all-host', 'Everyone can host sessions'), ('account-host', 'Anyone with an account can host'), ('member-host', 'Only group members can host'), ('limited-host', 'Only select users can host')], default='all-host', max_length=16, verbose_name='Who can host sessions?'),
        ),
    ]
