# Generated by Django 3.2.19 on 2024-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_host_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='web_policy',
            field=models.CharField(choices=[('disabled', 'Joining via web browser disabled'), ('manual', 'Joining via web browser only for manually-approved sessions'), ('passworded', 'Joining via web browser only for passworded and manually-approved sessions'), ('open', 'Joining via web browser allowed without restrictions')], default='disabled', max_length=16, verbose_name='How is joining via web browser handled?'),
        ),
    ]
