# Generated by Django 3.2.25 on 2025-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_web_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name="What's the rough region(s) of your server(s)?"),
        ),
    ]
