# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='Post',
            name='author_name',
            field=models.CharField(max_length=200, default='callaa'),
            preserve_default=False,
        )
    ]
