# Generated by Django 3.2.25 on 2025-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_author',
            field=models.BooleanField(default=False),
        ),
    ]
