# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.utils
import gallery.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=2000)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Favorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, upload_to=gallery.utils.UploadNameFromContent('gallery/avatar/', 'avatar'), validators=[gallery.utils.AvatarValidator(max_dims=(64, 64))])),
                ('bio', models.TextField(blank=True, help_text='Introduce yourself', max_length=10000)),
                ('show_nsfw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, upload_to=gallery.utils.UploadNameFromContent('gallery/groups/', 'logo'), validators=[gallery.utils.AvatarValidator(max_dims=(128, 128))])),
                ('description', models.TextField(blank=True, help_text='A short introduction of this group', max_length=10000)),
                ('server_address', models.CharField(blank=True, help_text="You group's home server", max_length=128, validators=[gallery.validators.hostname_validator])),
                ('website', models.URLField(blank=True, help_text="Your group's web site")),
                ('approve_joins', models.BooleanField(default=False, help_text='Moderator must approve new users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('member', 'Member'), ('mod', 'Moderator'), ('banned', 'Banned')], max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('submission_type', models.CharField(choices=[('picture', 'Picture')], max_length=16)),
                ('thumbnail', models.ImageField(upload_to='gallery/thumbs/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_nsfw', models.BooleanField(default=False, verbose_name='NSFW')),
                ('is_commenting_enabled', models.BooleanField(default=True, verbose_name='Allow comments')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gallery.Submission')),
                ('downscaled', models.ImageField(blank=True, upload_to='gallery/downscaled/')),
                ('fullsize', models.FileField(upload_to='gallery/full/')),
                ('filesize', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_submission_set', through='gallery.Favorited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='groups',
            field=models.ManyToManyField(blank=True, to='gallery.Group'),
        ),
        migrations.AddField(
            model_name='submission',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(through='gallery.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorited',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Submission'),
        ),
        migrations.AddField(
            model_name='favorited',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Submission'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='favorited',
            unique_together=set([('submission', 'user')]),
        ),
    ]
