# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-09 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favorited',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='favorited',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='favorited',
            name='user',
        ),
        migrations.RemoveField(
            model_name='galleryprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favorited',
        ),
        migrations.DeleteModel(
            name='GalleryProfile',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
