# Generated by Django 3.2.19 on 2024-02-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('raw_address', models.CharField(help_text='Verbatim email address used to register the account', max_length=255)),
                ('normalized_address', models.CharField(help_text='Normalized email address for querying', max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['normalized_address'], name='dpusers_ema_normali_3fee65_idx'),
        ),
    ]
