# Generated by Django 3.2.19 on 2024-02-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dpusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeletion',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('deactivated_at', models.DateTimeField(help_text='When deletion was initiated by the user')),
            ],
        ),
    ]
