#!/bin/sh
# Runs given command through manage.py.
set -e
cd "$(dirname "$0")/.."
set -x
exec docker compose -f docker/docker-compose.dev.yml run \
    --remove-orphans -w /website website \
    /website/docker/dev-run-in-venv-command ./manage.py "$@"
