# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 13:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The original username', max_length=22, validators=[django.core.validators.RegexValidator('^[^"]{1,22}$', message='Invalid username')])),
                ('normalized_name', models.CharField(blank=True, help_text='Normalized username for querying', max_length=22, unique=True)),
                ('is_mod', models.BooleanField(default=False, help_text='Enable moderator status for this username if the user has the moderator permission.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'id'],
                'permissions': (('moderator', 'Can activate moderator privileges'),),
            },
        ),
    ]
