# Generated by Django 3.2.19 on 2023-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0004_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='append_standard_reason',
            field=models.BooleanField(default=True, help_text='Will append the following: "If you think this ban is an error, take a look at https://drawpile.net/ban/ on how to contact a moderator."', verbose_name='Append standard text to reason'),
        ),
    ]
