# Generated by Django 3.2.19 on 2023-12-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0005_ban_append_standard_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='is_ghost',
            field=models.BooleanField(default=False, help_text='Enable ghost status for this username if the user has the ghost permission.'),
        ),
    ]
