# Generated by Django 3.2.19 on 2023-12-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0006_username_is_ghost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='username',
            options={'ordering': ['user', 'id'], 'permissions': (('moderator', 'Can activate moderator privileges'), ('ghost', 'Can activate ghost privileges'))},
        ),
    ]
