# Generated by Django 3.2.19 on 2024-02-10 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0007_alter_username_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='name',
            field=models.CharField(help_text='The original username', max_length=22, validators=[django.core.validators.RegexValidator('^[^"@]{1,22}$', message='Invalid username')]),
        ),
    ]
