# Generated by Django 3.2.19 on 2024-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0008_alter_username_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='normalized_name',
            field=models.CharField(blank=True, help_text='Normalized username for querying', max_length=255, unique=True),
        ),
    ]
