# Generated by Django 3.2.19 on 2024-02-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpauth', '0009_alter_username_normalized_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='username',
            index=models.Index(fields=['normalized_name'], name='dpauth_user_normali_c07dcb_idx'),
        ),
    ]
