# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('session_id', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=64)),
                ('users', models.IntegerField()),
                ('password', models.BooleanField()),
                ('nsfm', models.BooleanField()),
                ('title', models.CharField(max_length=128)),
                ('started', models.DateTimeField()),
                ('last_active', models.DateTimeField()),
                ('unlisted', models.BooleanField()),
                ('client_ip', models.CharField(max_length=64)),
                ('roomcode', models.CharField(max_length=16)),
                ('private', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'sessions',
                'ordering': ('-last_active',),
            },
        ),
    ]
