# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostban',
            fields=[
                ('host', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'hostbans',
                'managed': False,
                'ordering': ('host',),
            },
        ),
    ]
